### ISSUE TITLE
Source install on Slackware autogen.sh failure

### ISSUE THREAD

**Issue by mdinslage** [vaab/colour#59]
Hello, I am trying to install colour in Slackware 15 Beta 1 and I am getting this error when I run ./autogen.sh.  

`autogen.sh: error: Didn't find a git repository (or no tags found).  ``./autogen.sh`` uses git to create changelog and version information.`

As I understand it autogen.sh should create a Changelog.rst file needed by setup.py.   However I need to get past the above error.  Any help with this is appreciated.

Thank You.

**Comment by mdinslage** [comment]
Ok just a quick update, if I clone the git repo it works fine, this is just happening when downloading the releases (0.1.5).  Which is odd because the release and the latest git commit are basically the same.

**Comment by vaab** [comment]
Yes, sorry about that, but the auto-release of github (source packaged in a zip or equivalent) are not supported, but I can't deactivate them. The difference is crucial because `./autogen.sh` actually need the git history (and tags) to get the version information (from tags), and build the changelog (from git history). Your kind of report happen very rarely as usually, either people will get the distributed package through pip, or will clone it to work on the source.

**Comment by mdinslage** [comment]
Not a problem, its easy enough issue to get around.  I'll mark this as solved.
